### ISSUE TITLE
Wrong hex code of CREATE2

### ISSUE THREAD

**Issue by gsalzer** [usyd-blockchain/vandal#61]
In file `src/opcodes.py`, replace the line
```python3
CREATE2 = OpCode("CREATE2", 0xfb, 4, 1)
```
by
```python3
CREATE2 = OpCode("CREATE2", 0xf5, 4, 1)
```
The hex code of CREATE2 is `0xf5`, not `0xfb`.

Furthermore I suggest to integrate the lines below the headline
```python3
# New Byzantinium OpCodes for block.number >= BYZANTIUM_FORK_BLKNUM
```
into the general list of instructions, since the Constantinople opcodes, even newer than Byzantinium, have been integrated there as well.

**Comment by b-scholz** [comment]
@gsalzer - please could you create a pull-request. I am happy to accept.

**Comment by gsalzer** [comment]
@b-scholz done
