### ISSUE TITLE
Python 3.8 compatibility: time.clock no longer exists

### ISSUE THREAD

**Issue by gsalzer** [usyd-blockchain/vandal#62]
In `src/dataflow.py`, replace all occurrences of `time.clock()` by `time.process_time()`.
`time.clock()` has been deprecated since Python 3.3 and has been removed in Python 3.8.

If you are a prefectionist, you might also want to remove a typo:
Replace
```python
"blocks were cloned on average of %.2f times each."
```
either by
```python
"blocks were cloned an average of %.2f times each."
```
(`on` replaced by `an`), or by
```python
"blocks were cloned, on average, %.2f times each."
```
(`of` removed).

**Comment by b-scholz** [comment]
@gsalzer - please can you make a pull-request for this.

**Comment by gsalzer** [comment]
@b-scholz done
