### ISSUE TITLE
Nondeterminism makes testing expected output hard

### ISSUE THREAD

**Issue by 0xl3x1** [usyd-blockchain/vandal#8]
Currently the output of bin/decompile can differ each time it is run on the same input. This is likely due to our use of unordered collections such as `dict`. Unfortunately, this makes output testing of the kind being implemented in [lexibrent:bats-tests](https://github.com/lexibrent/vandal/tree/bats-tests) impossible.

The solution I propose is updating the functions that produce textual output so that all non-deterministically ordered data structures are sorted.

For example, recently I saw these two different outputs for `basic_optimized.dasm`:

```
5c5
< Successors: [0x1a, 0x18]
---
> Successors: [0x18, 0x1a]
108a109
> --
```

My proposed solution is to sort the preds and succs lists, and any other relevant structures in our output rendering functions.

**Comment by zyzek** [comment]
I wonder if upgrading to python 3.6+ will solve this; in the latest release, dicts are now ordered (by insertion order) https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-compactdict

Or we could switch to OrderedDicts, or some other data structure. I'm not sure of the performance ramifications of this.

**Comment by MKong** [comment]
ordered dicts should work fine. Performance should be the same as it currently is (assuming we don't repeatedly sort the ordered dict), as the ordering should be maintained based on what elements come in first.

**Comment by 0xl3x1** [comment]
@zyzek 

> The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon

Hmm
